version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "20:00"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: github.com/aws/aws-sdk-go
        versions:
          - ">= 1.35"
