name: goreleaser

on:
  push:
    tags:
      - "v2.*"

jobs:
  goreleaser:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
          cache-dependency-path: v2/go.sum

      - name: Configure AWS Credentials
        uses: fuller-inc/actions-aws-assume-role@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::445285296882:role/rpm-repository-users-RdsMySQLDeployRole-XDibbGv88soX
          role-session-tagging: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
          workdir: v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
