name: update
on:
  schedule:
    - cron: "23 6 * * *"
  workflow_dispatch:

jobs:
  update:
    name: update
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Update the Certificates v1
        run: go generate ./...

      - name: Update the Certificates v2
        run: go generate ./...
        working-directory: v2

      - name: Commit and Push Changes
        uses: shogo82148/actions-commit-and-create-pr@v1
